// <auto-generated />
using System;
using System.Collections.Generic;
using CatalogingSystem.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogingSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogingSystem.Core.Entities.ArchivoAdministrativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("archivoDocumental")
                        .HasColumnType("text");

                    b.Property<string>("asunto")
                        .HasColumnType("text");

                    b.Property<string>("documentoOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("expediente")
                        .HasColumnType("bigint");

                    b.Property<string>("expedienteAnterior")
                        .HasColumnType("text");

                    b.Property<DateTime?>("fechaFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fechaInicial")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("historial")
                        .HasColumnType("text");

                    b.Property<string>("institucion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<bool?>("peticionTransferencia")
                        .HasColumnType("boolean");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<string>("unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("expediente")
                        .IsUnique();

                    b.ToTable("ArchivosAdministrativos");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.GraphicDocumentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("expediente")
                        .HasColumnType("bigint");

                    b.Property<string>("generalObservations")
                        .HasColumnType("text");

                    b.Property<string>("genericControlNumber")
                        .HasColumnType("text");

                    b.Property<List<string>>("imageUrls")
                        .HasColumnType("text[]");

                    b.Property<long>("inventory")
                        .HasColumnType("bigint");

                    b.Property<string>("specificControlNumber")
                        .HasColumnType("text");

                    b.Property<List<string>>("supportTypes")
                        .HasColumnType("text[]");

                    b.Property<string>("technicalData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("expediente")
                        .IsUnique();

                    b.ToTable("GraphicDocumentations");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.Identification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("expediente")
                        .HasColumnType("bigint");

                    b.Property<string>("genericClassification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("inventory")
                        .HasColumnType("bigint");

                    b.Property<int>("numberOfObjects")
                        .HasColumnType("integer");

                    b.Property<string>("objectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("expediente");

                    b.ToTable("Identifications");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int?>("PermissionLevel")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.GraphicDocumentation", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "ArchivoAdministrativo")
                        .WithOne()
                        .HasForeignKey("CatalogingSystem.Core.Entities.GraphicDocumentation", "expediente")
                        .HasPrincipalKey("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "expediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CatalogingSystem.Core.Entities.Dimensions", "dimensions", b1 =>
                        {
                            b1.Property<Guid>("GraphicDocumentationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<double>("Height")
                                .HasColumnType("double precision");

                            b1.Property<double>("Width")
                                .HasColumnType("double precision");

                            b1.HasKey("GraphicDocumentationId");

                            b1.ToTable("GraphicDocumentations");

                            b1.WithOwner()
                                .HasForeignKey("GraphicDocumentationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.ImageAuthor", "imageAuthor", b1 =>
                        {
                            b1.Property<Guid>("GraphicDocumentationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Department")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("IdentityCard")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Institution")
                                .HasColumnType("text");

                            b1.Property<string>("InstitutionalId")
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Locality")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("References")
                                .HasColumnType("text");

                            b1.HasKey("GraphicDocumentationId");

                            b1.ToTable("GraphicDocumentations");

                            b1.WithOwner()
                                .HasForeignKey("GraphicDocumentationId");
                        });

                    b.Navigation("ArchivoAdministrativo");

                    b.Navigation("dimensions");

                    b.Navigation("imageAuthor");
                });

            modelBuilder.Entity("CatalogingSystem.Core.Entities.Identification", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.ArchivoAdministrativo", "ArchivoAdministrativo")
                        .WithMany()
                        .HasForeignKey("expediente")
                        .HasPrincipalKey("expediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CatalogingSystem.Core.Entities.Author", "author", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("BirthDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("BirthPlace")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("DeathDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DeathPlace")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Material", "material", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Colors")
                                .HasColumnType("text");

                            b1.Property<string>("DescribedPart")
                                .HasColumnType("text");

                            b1.Property<string>("MaterialName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Section", "section", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Courtyard")
                                .HasColumnType("text");

                            b1.Property<string>("DisplayCase")
                                .HasColumnType("text");

                            b1.Property<string>("Easel")
                                .HasColumnType("text");

                            b1.Property<string>("Others")
                                .HasColumnType("text");

                            b1.Property<string>("Panel")
                                .HasColumnType("text");

                            b1.Property<string>("Pillar")
                                .HasColumnType("text");

                            b1.Property<string>("Room")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Storage")
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.SpecificName", "specificName", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("GenericName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("RelatedTerms")
                                .HasColumnType("text");

                            b1.Property<string>("SpecificTerms")
                                .HasColumnType("text");

                            b1.Property<string>("UsedBy")
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Technique", "techniques", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("DescribedPart")
                                .HasColumnType("text");

                            b1.Property<string>("TechniqueName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Title", "title", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Attribution")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Translation")
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.OwnsOne("CatalogingSystem.Core.Entities.Typology", "typology", b1 =>
                        {
                            b1.Property<Guid>("IdentificationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Class")
                                .HasColumnType("text");

                            b1.Property<string>("Order")
                                .HasColumnType("text");

                            b1.Property<string>("Subclass")
                                .HasColumnType("text");

                            b1.Property<string>("Suborder")
                                .HasColumnType("text");

                            b1.Property<string>("Subtype")
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IdentificationId");

                            b1.ToTable("Identifications");

                            b1.WithOwner()
                                .HasForeignKey("IdentificationId");
                        });

                    b.Navigation("ArchivoAdministrativo");

                    b.Navigation("author")
                        .IsRequired();

                    b.Navigation("material")
                        .IsRequired();

                    b.Navigation("section")
                        .IsRequired();

                    b.Navigation("specificName")
                        .IsRequired();

                    b.Navigation("techniques")
                        .IsRequired();

                    b.Navigation("title")
                        .IsRequired();

                    b.Navigation("typology")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogingSystem.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CatalogingSystem.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
